version: "3.5"
services:
  php:
    build:
      context: ./.docker/php/fpm
      args:
       PHP_VERSION: $PHP_VERSION
    working_dir: /var/www/
    volumes:
      - $PROJECT_DIRECTORY:/var/www/
      - $PROJECT_DIRECTORY:/var/www/
      - ./.docker/php/fpm/php.ini-development:/usr/local/etc/php/php.ini
    restart: always
  php5:
    build:
      context: ./.docker/php/fpm/php5/
      args:
       PHP5_VERSION: ${PHP5_VERSION}
    working_dir: /var/www/
    volumes:
      - $PROJECT_DIRECTORY:/var/www/
    restart: always
  nginx:
    build:
      context: ./.docker/nginx/
      args:
       NGINX_VERSION: ${NGINX_VERSION}
    working_dir: /var/www
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/certificates:/etc/certificates
      - $PROJECT_DIRECTORY:/var/www/
    restart: always
    ports:
      - $NGINX_PORT:80
      - 443:443

  # The Database
  database:
    image: mysql:${MYSQL_VERSION:-latest}
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_USER=remote"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT=3306"
    ports:
      - $PHPMYADMIN_PORT:80
    restart: always

volumes:
  dbdata:
