version: "3.5"
services:
  php:
    build:
      context: ./.docker/php/fpm
      args:
       PHP_VERSION: $PHP_VERSION
    working_dir: /var/www/
    volumes:
      - /Users/hieupv/Works/Projects:/var/www/
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always
  php5:
    build:
      context: ./.docker/php/fpm/php5/
      args:
       PHP5_VERSION: ${PHP5_VERSION}
    working_dir: /var/www/
    volumes:
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always
  nginx:
    build:
      context: ./.docker/nginx/
      args:
       NGINX_VERSION: ${NGINX_VERSION}
    working_dir: /var/www
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always
    ports:
      - 8800:80

  # The Database
  database:
    image: mysql:${MYSQL_VERSION:-latest}
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_USER=remote"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT=3306"
    ports:
      - "8801:80"
    restart: always

volumes:
  dbdata:
