version: "3.5"
services:
  # The Application
  php:
    build:
      context: ./.docker/
      dockerfile: php72.dockerfile
    working_dir: /var/www/
    volumes:
      - /Users/hieupv/Works/Projects:/var/www/
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always
  php56:
    build:
      context: ./.docker/
      dockerfile: php56.dockerfile
    working_dir: /var/www/
    volumes:
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always

  # The Web Server
  nginx:
    build:
      context: ./.docker/
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - /Users/hieupv/Works/Projects:/var/www/
    restart: always
    ports:
      - 8800:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      # - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=remote"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT=3306"
    ports:
      - "8801:80"
    restart: always

volumes:
  dbdata: