version: '3'
services:

  # The Application
  php:
    build:
      context: ./
      dockerfile: php7.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/

  # The Web Server
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
